# Generated by Django 3.1.1 on 2020-09-15 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='members_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=250)),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('profile_img', models.ImageField(upload_to='images/profile_imgs/')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
