# Generated by Django 3.1.1 on 2020-09-25 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0006_remove_discussion_read'),
        ('members_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fav_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_course', to='admin_portal.course')),
            ],
        ),
    ]
