# Generated by Django 3.1.1 on 2020-11-06 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0010_auto_20201106_1243'),
        ('members_portal', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeUnlike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('unlike', models.IntegerField()),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
