# Generated by Django 3.1.1 on 2020-11-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_portal', '0004_likeunlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeunlike',
            name='unlike',
        ),
        migrations.AlterField(
            model_name='likeunlike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
