# Generated by Django 3.1.1 on 2020-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_portal', '0005_auto_20201107_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeunlike',
            name='like',
            field=models.BooleanField(null=True),
        ),
    ]
