# Generated by Django 3.1.1 on 2020-11-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_portal', '0009_addreview_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_profile',
            name='youtube',
        ),
        migrations.AddField(
            model_name='members_profile',
            name='phone_number',
            field=models.CharField(default='00000', max_length=200),
        ),
    ]
