# Generated by Django 3.1.1 on 2020-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_portal', '0011_auto_20201115_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_profile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members_profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members_profile',
            name='profession',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='members_profile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members_profile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
