# Generated by Django 3.1.1 on 2020-09-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_membersinfo_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_email', models.EmailField(max_length=254)),
                ('card_last_digit', models.IntegerField()),
                ('card_type', models.CharField(max_length=30)),
                ('card_exp_month', models.CharField(max_length=30)),
                ('card_exp_year', models.CharField(max_length=50)),
                ('card_bank', models.CharField(max_length=50)),
                ('card_auth', models.CharField(max_length=50)),
                ('card_account_name', models.CharField(max_length=100)),
                ('card_first_name', models.CharField(max_length=50)),
                ('card_last_name', models.CharField(max_length=50)),
            ],
        ),
    ]
