# Generated by Django 3.1.1 on 2020-09-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_account_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
