# Generated by Django 3.1.1 on 2020-11-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20200927_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersinfo',
            name='signal_notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membersinfo',
            name='signal_update',
            field=models.BooleanField(default=False),
        ),
    ]
