# Generated by Django 3.1.1 on 2020-09-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('membership', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('cover_img', models.ImageField(upload_to='images/coverImg')),
                ('material', models.FileField(upload_to='materials/')),
                ('volume', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
