# Generated by Django 3.1.1 on 2020-09-22 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_overview',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
