# Generated by Django 3.1.1 on 2020-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_auto_20200924_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
