# Generated by Django 3.1.1 on 2020-09-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_discussion_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='read',
        ),
    ]
