# Generated by Django 3.1.1 on 2020-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
