# Generated by Django 3.1.1 on 2020-11-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0008_discussion_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='comment_replied',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
