# Generated by Django 3.1.1 on 2020-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_discussion_comment_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='comment_replied',
            field=models.IntegerField(default=0),
        ),
    ]
