# Generated by Django 3.1.1 on 2020-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0010_auto_20201106_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=250)),
            ],
        ),
    ]
