# Generated by Django 3.1.1 on 2020-11-06 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0011_discussiontopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopics',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
