# Generated by Django 3.1.1 on 2020-11-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_discussiontopics_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='like',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='unlike',
        ),
    ]
