# Generated by Django 3.1.1 on 2020-11-06 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0013_auto_20201106_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='admin_portal.discussiontopics'),
            preserve_default=False,
        ),
    ]
