# Generated by Django 3.1.1 on 2020-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0015_auto_20201107_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='unlike_count',
            field=models.IntegerField(default=0),
        ),
    ]
