# Generated by Django 3.1.1 on 2020-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0017_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
