# Generated by Django 3.1.1 on 2020-11-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0018_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50)),
                ('lot_size', models.IntegerField()),
            ],
        ),
    ]
