# Generated by Django 3.1.1 on 2020-11-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0019_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='lot_size',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
