# Generated by Django 3.1.1 on 2020-11-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0020_auto_20201115_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='lowest_risk_dollar',
            field=models.DecimalField(decimal_places=2, default=20.8, max_digits=20),
        ),
        migrations.AddField(
            model_name='market',
            name='points',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='market',
            name='lot_size',
            field=models.DecimalField(decimal_places=3, default=23.9, max_digits=30),
        ),
    ]
