# Generated by Django 3.1.1 on 2020-11-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0021_auto_20201116_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='lot_size',
            field=models.DecimalField(decimal_places=10, default=23.9, max_digits=30),
        ),
        migrations.AlterField(
            model_name='market',
            name='lowest_risk_dollar',
            field=models.DecimalField(decimal_places=10, default=20.8, max_digits=20),
        ),
    ]
