# Generated by Django 3.1.1 on 2020-11-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0022_auto_20201116_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='lot_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='lowest_risk_dollar',
            field=models.FloatField(),
        ),
    ]
