# Generated by Django 3.1.1 on 2020-11-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0023_auto_20201116_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='points',
            field=models.FloatField(),
        ),
    ]
